package client.GUI;

import client.Controllers.AuthorizationController;
import client.Controllers.LocaleController;
import client.Controllers.ResourceBundlesController;
import common.Exceptions.LocalizedException;
import common.Exceptions.LocalizedMessage;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Arrays;
import java.util.Locale;
import java.util.ResourceBundle;

public class SignUpForm {
    private JPanel signUpRootPanel;
    private JLabel signUpLabel;
    private JPanel signUpPanel;
    private JTextField usernameTextField;
    private JTextField passwordTextField;
    private JTextField confirmPasswordTextField;
    private JButton signUpButton;
    private JLabel usernameLabel;
    private JLabel passwordLabel;
    private JLabel confirmPasswordLabel;
    private JLabel welcomeLabel;
    private JComboBox localeComboBox;
    private JLabel localeLabel;
    private JLabel backToLogInLabel;
    private JPanel leftPanel;
    private JPanel rightPanel;

    public SignUpForm() {
        $$$setupUI$$$();
        updateLocale();
        signUpButton.addActionListener(new SignUpButtonListener());
        localeComboBox.addActionListener(new LocaleComboBoxListener());
        backToLogInLabel.addMouseListener(new BackToLogInLabelListener());
    }

    private void updateLocale() {
        ResourceBundle labels = ResourceBundlesController.getInstance().getSignUpBundle();
        signUpLabel.setText(labels.getString("signUpLabel"));
        usernameLabel.setText(labels.getString("usernameLabel"));
        passwordLabel.setText(labels.getString("passwordLabel"));
        confirmPasswordLabel.setText(labels.getString("confirmPasswordLabel"));
        welcomeLabel.setText(labels.getString("welcomeLabel"));
        signUpButton.setText(labels.getString("signUpButton"));
        backToLogInLabel.setText(labels.getString("backToLogInLabel"));
        localeLabel.setText(labels.getString("localeLabel") + ":");
    }

    private void createUIComponents() {
        localeComboBox = new JComboBox<String>();
        LocaleController.getInstance().getLocaleNames().forEach(localeComboBox::addItem);
        localeComboBox.setSelectedIndex(LocaleController.getInstance().getCurrentLocaleNumber());
    }

    private class BackToLogInLabelListener extends MouseAdapter {
        @Override
        public void mouseClicked(MouseEvent e) {
            super.mouseClicked(e);
            GUIController.getInstance().setState(GUIStates.LOG_IN);
        }
    }

    private class LocaleComboBoxListener implements ActionListener {
        @Override
        public void actionPerformed(ActionEvent e) {
            LocaleController.getInstance().setLocale(localeComboBox.getSelectedIndex());
            updateLocale();
        }
    }

    private class SignUpButtonListener implements ActionListener {
        @Override
        public void actionPerformed(ActionEvent e) {
            String username = usernameTextField.getText();
            String password = passwordTextField.getText();
            String confirmedPassword = confirmPasswordTextField.getText();
            try {
                AuthorizationController.singUp(username, password, confirmedPassword);
                GUIController.getInstance().showInfoMessage(new LocalizedMessage("authorizationDoneMessage"));
                GUIController.getInstance().setState(GUIStates.LOG_IN);
            } catch (LocalizedException ex) {
                GUIController.getInstance().showErrorMessage(ex);
            }
        }
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        signUpRootPanel = new JPanel();
        signUpRootPanel.setLayout(new GridBagLayout());
        leftPanel = new JPanel();
        leftPanel.setLayout(new BorderLayout(0, 0));
        leftPanel.setMinimumSize(new Dimension(157, 282));
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 0.5;
        gbc.weighty = 0.5;
        gbc.fill = GridBagConstraints.BOTH;
        signUpRootPanel.add(leftPanel, gbc);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        leftPanel.add(panel1, BorderLayout.NORTH);
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(10, 10, 0, 0);
        panel1.add(localeComboBox, gbc);
        localeLabel = new JLabel();
        Font localeLabelFont = this.$$$getFont$$$(null, Font.PLAIN, 16, localeLabel.getFont());
        if (localeLabelFont != null) localeLabel.setFont(localeLabelFont);
        localeLabel.setText("Language:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(10, 10, 0, 0);
        panel1.add(localeLabel, gbc);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridBagLayout());
        leftPanel.add(panel2, BorderLayout.CENTER);
        signUpPanel = new JPanel();
        signUpPanel.setLayout(new GridBagLayout());
        signUpPanel.setMinimumSize(new Dimension(252, 282));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        panel2.add(signUpPanel, gbc);
        signUpLabel = new JLabel();
        Font signUpLabelFont = this.$$$getFont$$$(null, Font.PLAIN, 16, signUpLabel.getFont());
        if (signUpLabelFont != null) signUpLabel.setFont(signUpLabelFont);
        signUpLabel.setText("Enter information, please");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        signUpPanel.add(signUpLabel, gbc);
        usernameLabel = new JLabel();
        Font usernameLabelFont = this.$$$getFont$$$(null, Font.PLAIN, 16, usernameLabel.getFont());
        if (usernameLabelFont != null) usernameLabel.setFont(usernameLabelFont);
        usernameLabel.setText("Enter username");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        signUpPanel.add(usernameLabel, gbc);
        usernameTextField = new JTextField();
        Font usernameTextFieldFont = this.$$$getFont$$$(null, Font.PLAIN, 16, usernameTextField.getFont());
        if (usernameTextFieldFont != null) usernameTextField.setFont(usernameTextFieldFont);
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        signUpPanel.add(usernameTextField, gbc);
        passwordLabel = new JLabel();
        Font passwordLabelFont = this.$$$getFont$$$(null, Font.PLAIN, 16, passwordLabel.getFont());
        if (passwordLabelFont != null) passwordLabel.setFont(passwordLabelFont);
        passwordLabel.setText("Enter password");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 6;
        gbc.anchor = GridBagConstraints.WEST;
        signUpPanel.add(passwordLabel, gbc);
        passwordTextField = new JTextField();
        Font passwordTextFieldFont = this.$$$getFont$$$(null, Font.PLAIN, 16, passwordTextField.getFont());
        if (passwordTextFieldFont != null) passwordTextField.setFont(passwordTextFieldFont);
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 7;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        signUpPanel.add(passwordTextField, gbc);
        confirmPasswordLabel = new JLabel();
        Font confirmPasswordLabelFont = this.$$$getFont$$$(null, Font.PLAIN, 16, confirmPasswordLabel.getFont());
        if (confirmPasswordLabelFont != null) confirmPasswordLabel.setFont(confirmPasswordLabelFont);
        confirmPasswordLabel.setText("Confirm password");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 9;
        gbc.anchor = GridBagConstraints.WEST;
        signUpPanel.add(confirmPasswordLabel, gbc);
        confirmPasswordTextField = new JTextField();
        Font confirmPasswordTextFieldFont = this.$$$getFont$$$(null, Font.PLAIN, 16, confirmPasswordTextField.getFont());
        if (confirmPasswordTextFieldFont != null) confirmPasswordTextField.setFont(confirmPasswordTextFieldFont);
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 10;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        signUpPanel.add(confirmPasswordTextField, gbc);
        signUpButton = new JButton();
        Font signUpButtonFont = this.$$$getFont$$$(null, Font.PLAIN, 16, signUpButton.getFont());
        if (signUpButtonFont != null) signUpButton.setFont(signUpButtonFont);
        signUpButton.setText("Sign Up");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 12;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(5, 5, 5, 5);
        signUpPanel.add(signUpButton, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.VERTICAL;
        signUpPanel.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.fill = GridBagConstraints.VERTICAL;
        signUpPanel.add(spacer2, gbc);
        final JPanel spacer3 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 8;
        gbc.fill = GridBagConstraints.VERTICAL;
        signUpPanel.add(spacer3, gbc);
        final JPanel spacer4 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 11;
        gbc.fill = GridBagConstraints.VERTICAL;
        signUpPanel.add(spacer4, gbc);
        welcomeLabel = new JLabel();
        Font welcomeLabelFont = this.$$$getFont$$$(null, -1, 24, welcomeLabel.getFont());
        if (welcomeLabelFont != null) welcomeLabel.setFont(welcomeLabelFont);
        welcomeLabel.setText("Welcome to the app");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        signUpPanel.add(welcomeLabel, gbc);
        backToLogInLabel = new JLabel();
        Font backToLogInLabelFont = this.$$$getFont$$$(null, Font.PLAIN, 16, backToLogInLabel.getFont());
        if (backToLogInLabelFont != null) backToLogInLabel.setFont(backToLogInLabelFont);
        backToLogInLabel.setForeground(new Color(-13205275));
        backToLogInLabel.setText("Back to Log In");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 13;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        signUpPanel.add(backToLogInLabel, gbc);
        rightPanel = new JPanel();
        rightPanel.setLayout(new GridBagLayout());
        rightPanel.setBackground(new Color(-11961296));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 0.5;
        gbc.weighty = 0.5;
        gbc.fill = GridBagConstraints.BOTH;
        signUpRootPanel.add(rightPanel, gbc);
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return signUpRootPanel;
    }

}
